version: "3.9"
services:
  runner:
    build: ./runner
    volumes:
      - ./config:/config
      - ./backups:/backups
      - runner-data:/data
    ports:
      - "8080:8000"
    environment:
      - CONFIG_PATH=/config/config.yaml
    networks:
      - default
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=analytics
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - default
volumes:
  postgres-data:
  mongo-data:
  runner-data:
networks:
  default:
