[supervisord]
nodaemon=true

[program:scheduler]
command=python /usr/src/app/scheduler.py
autostart=true
autorestart=false
startsecs=0

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:api]
command=python /usr/src/app/api.py
autostart=true
autorestart=true
